controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: position_controllers/JointGroupPositionController

    base_controller:
      type: diff_drive_controller/DiffDriveController

arm_controller:
  ros__parameters:
    joints:
      - joint_cronstein
      - joint_first_part
      - joint_second_part
      - joint_head
    interface_name: position

base_controller:
  ros__parameters:
    left_wheel_names: ["joint_left_front_base_link_wheel", "joint_left_rear_base_link_wheel"]
    right_wheel_names: ["joint_right_front_base_link_wheel", "joint_right_rear_base_link_wheel"]
    wheel_separation: 0.55
    wheel_radius: 0.08
    use_stamped_vel: false
